declare var selection: {
  numberOfNodesSelected(): number;
  selectedNode(i: number): string;
  selectedWaypoint(i: number): string;
  numberOfColumnsSelected(): number;
  selectedColumn(i: number): string;
  clearSelection(): boolean;
  addNodeToSelection(node: string): boolean;
  addNodesToSelection(nodes: any): void;
  removeNodeFromSelection(node: string): boolean;
  addBackdropToSelection(backdrop: any): boolean;
  removeBackdropFromSelection(backdrop: any): boolean;
  addBackdropToSelection(groupPath: string, idx: number): boolean;
  removeBackdropFromSelection(groupPath: string, idx: number): boolean;
  addWaypointToSelection(waypoint: string): boolean;
  removeWaypointFromSelection(waypoint: string): boolean;
  addColumnToSelection(column: string): boolean;
  addDrawingColumnToSelection(columnName: string): boolean;
  extendSelectionWithColumn(columnName: string): boolean;
  setSelectionFrameRange(start: number, length: number): void;
  isSelectionRange(): boolean;
  startFrame(): number;
  numberOfFrames(): number;
  selectAll(): void;
  selectedNodes(): any;
  selectedWaypoints(): any;
  selectedBackdrops(): any;
  subSelectionForNode(node: string): any;
  addSubSelectionForNode(node: string, subSelection: any): boolean;
  clearSubSelectionForNode(node: string): boolean;
  attributeFromSubSelectionId(node: string, subSelectionId: number): any;
  subSelectionIdFromAttribute(attribute: any): number;
};
